name: Build, Push, and Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest


  deploy:
    name: Deploy to Azure Ubuntu Server
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy Application
      env:
        SSH_HOST: ${{ secrets.AZURE_SERVER_HOST }}
        SSH_USER: ${{ secrets.AZURE_SERVER_USER }}
        SSH_PASS: ${{ secrets.AZURE_SERVER_PASS }}
      run: |
        # Pull the latest Docker image and restart the container
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
        docker stop nextjs-container || true
        docker rm nextjs-container || true
        docker run -d --name nextjs-container -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
        EOF
     
        
