name: Build, Push, and Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest


  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y sshpass
  
      - name: Deploy using Docker Compose
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SERVER_PASS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $AZURE_SERVER_USER@$AZURE_SERVER_HOST << 'EOF'
          cd /path/to/docker-compose
          docker-compose pull
          docker-compose down
          docker-compose up -d
          EOF
        env:
          SSH_HOST: ${{ secrets.AZURE_SERVER_HOST }}
          SSH_USER: ${{ secrets.AZURE_SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_SERVER_PASS }}
           
            
