name: Build, Push, and Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

  deploy:
    name: Deploy to Azure Ubuntu Server using Docker Compose
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Install SSH Client and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass git docker-compose

    - name: Checkout Code (again for the deployment)
      uses: actions/checkout@v3

    - name: Deploy Application using Docker Compose
      env:
        SSH_HOST: ${{ secrets.AZURE_SERVER_HOST }}
        SSH_USER: ${{ secrets.AZURE_SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.AZURE_SERVER_SSH_KEY }}
      run: |
        # Set up SSH key for authentication
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # SSH into the server and deploy using Docker Compose
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
        # Create the 'app' directory in the home directory if it doesn't exist
        mkdir -p ~/app

        # Navigate to the 'app' directory
        cd ~/app

        # Clone the repository (or pull if it already exists)
        git clone https://github.com/your_username/your_repository.git . || git pull origin main

        # Pull the latest Docker images and update the containers
        docker-compose pull
        docker-compose down
        docker-compose up -d
        EOF
