name: Build, Push, and Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest


  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy with Docker Compose
      env:
        SSH_HOST: ${{ secrets.PRODUCTION_SERVER_HOST }}
        SSH_USER: ${{ secrets.PRODUCTION_SERVER_USER }}
        SSH_PASS: ${{ secrets.PRODUCTION_SERVER_PASS }}
      run: |
        # SSH into the server and deploy using Docker Compose
        sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
        cd /path/to/docker-compose  # Navigate to the directory with docker-compose.yml
        docker-compose pull         # Pull the latest image
        docker-compose down         # Stop and remove current containers
        docker-compose up -d        # Start updated containers in detached mode
        EOF
     
        
